### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by elect86** [krakowski/gradle-jextract#1] opened 2021-06-07 20:56 UTC
Hi,

cool project!

However whenever I try sync'ing I'm getting the following:

> Execution failed for task ':jextract'.
> jextract binary could not be found (JVM_HOME=/home/elect/.jdks/openjdk-15.0.2)

Although I do have

`java.toolchain.languageVersion.set(JavaLanguageVersion.of(17))`

Unfortunately Gradle 7.0.2 seems to be compatible up to jdk16.. how do you get the whole thing working?

Also, what about a kotlin conversion? Because I'd like to add some other options/features

**Comment by krakowski** [comment] 2021-06-08 21:21
Hi @elect86,

the [`jextract`](https://github.com/openjdk/panama-foreign/blob/foreign-jextract/doc/panama_jextract.md) tool is currently only available in builds of the [JDK that include Project Panama](https://github.com/openjdk/panama-foreign). I have set up a pipeline for research purposes that builds nightly builds of the current `master` branch and uploads them to a [web server](https://coconucos.cs.hhu.de/forschung/jdk). This is also compatible with [SDKMAN!](https://sdkman.io/) through a install script (`curl -s "https://coconucos.cs.hhu.de/forschung/jdk/install" | bash`).

Besides this repository, there is [another one](https://github.com/krakowski/jextract-demo) (which I just linked inside the README) showcasing the usage of this plugin with a simple example. I have also included a note that describes how to deal with Java versions that are not compatible with Gradle using this plugin.

> - Gradle is often incompatible with newly released Java versions, resulting in the error message `Unsupported class file major version`. The `gradle-jextract` plugin can work around this by using a different JDK for compiling the sources. To enable this feature the `javaHome` property has to be set within your global `gradle.properties` usually located inside `${HOME}/.gradle`.
>
>  ```
>  javaHome=/path/to/your/panama/java/home
>  ```

> Also, what about a kotlin conversion? Because I'd like to add some other options/features

Converting the plugin to Kotlin isn't my top priority right now, however I would be happy to accept pull requests. What features do you have in mind?

**Comment by elect86** [comment] 2021-06-08 22:01
Yeah, that jdk (15) was being picked up whenever I was launching anything from the Idea UI. 

It turns out I had to add [this](https://github.com/elect86/test/blob/master/build.gradle.kts#L36-L38) as well

```
tasks.withType<JavaExec>().configureEach {
    javaLauncher.set(javaToolchains.launcherFor(java.toolchain))
}
```
This is known [issue](https://github.com/gradle/gradle/issues/16791)

> Converting the plugin to Kotlin isn't my top priority right now, however I would be happy to accept pull requests. What features do you have in mind?

I can PR quite quick, I've basically reached a [stable point](https://github.com/elect86/jextract)

Regarding the features

1) since I'd expect:
- almost all users using the EA builds on https://jdk.java.net/panama/
- Gradle isn't yet compatible with jdk 17, this means using a specific toolchain for build and run the code
- people not installing experimental temporal jdks in normal standard locations, this means suggesting Gradle via [`org.gradle.java.installations.paths`](https://github.com/elect86/test/blob/master/gradle.properties#L3)

Therefore I'd get rid of `javaHome` in favour of [defaulting](https://github.com/elect86/jextract/blob/master/plugin/src/main/kotlin/jextract/JextractTask.kt#L28-L34) to `jdk-17`, extracted from that gradle property, which is exactly the name of the EA builds folder (at the moment a little more relaxed looking only for location paths containing `jdk` and `17`)

2) give an option to append a `jextract` run with `--source` and include them in Idea (the decompiling of `.class` file is crap), but I don't know how to do that and I haven't still investigated into

3) I'd cache the `jextract` task execution, if nothing changed in the configuration `jextract { }`, then I'd not like to run it again, but I don't know how yet as well

4) I'd love to offer some predefined library configurations, such as opengl
```
jextract {
   library.opengl()
}
```
And then within that call, we look which platform are we on and we set everything accordingly


Ps: I also haven't still figured out why:

- this:
```
                target.tasks.withType<JavaCompile> {
                    options.apply {
                        isFork = true
                        forkOptions.javaHome = target.file(jex.javaHome.get())
                    }
                }
```
fires
> Must not use `javaHome` property on `ForkOptions` together with `javaCompiler` property

- the [kotlin counterpart](https://github.com/elect86/test/blob/master/src/main/kotlin/main.kt) of the OpenGL Teapot example is causing me problems and I have no idea why: tons of unresolved, such as `import jdk.incubator.foreign.CLinker`. The [java one](https://github.com/elect86/test/blob/master/src/main/java/Teapot.java) runs flawless

**Comment by krakowski** [comment] 2021-06-09 14:29
> Therefore I'd get rid of `javaHome` in favour of [defaulting](https://github.com/elect86/jextract/blob/master/plugin/src/main/kotlin/jextract/JextractTask.kt#L28-L34) to `jdk-17`, extracted from that gradle property, which is exactly the name of the EA builds folder (at the moment a little more relaxed looking only for location paths containing `jdk` and `17`)

A very good remark, although I wouldn't hardcode it to `jdk-17` (or filter it based on `jdk` and `17`). At the moment Gradle does detect my local nightly build when calling the `javaToolchains` task.

```
 + N/A JDK 17-internal
     | Location:           /home/krakowski/.sdkman/candidates/java/panama
     | Language Version:   17
     | Vendor:             N/A
     | Is JDK:             true
     | Detected by:        SDKMAN!
```

According to [this Gradle documentation](https://docs.gradle.org/current/userguide/toolchains.html) it should be possible to get a list of detected JDKs and select the appropriate one (at the moment `Language Version == 17`). If a user installs the JDK in a non-standard location, it would still be possible to specify it using `org.gradle.java.installations.paths`, as you said.

> 1. give an option to append a `jextract` run with `--source` and include them in Idea (the decompiling of `.class` file is crap), but I don't know how to do that and I haven't still investigated into

This is already possible via `sourceMode = true`. Applying the `idea` plugin should also make IntelliJ detect those sources. The generated files should be located inside `build/generated/jextract`.

> 2. I'd cache the `jextract` task execution, if nothing changed in the configuration `jextract { }`, then I'd not like to run it again, but I don't know how yet as well

This is integrated as well. Just execute the `jextract` task twice in a row. The second time it should print `SKIPPED`.

> 3. I'd love to offer some predefined library configurations, such as opengl
> 
> ```
> jextract {
>    library.opengl()
> }
> ```
> And then within that call, we look which platform are we on and we set everything accordingly

The only way I can imagine this working is by providing a path-independent collection of header files within a header file [like in the jextract-demo](https://github.com/krakowski/jextract-demo/blob/master/src/main/c/stdio.h). These files could be hosted on GitHub inside a repository using folders named `linux`, `windows`, etc.

Also, please keep in mind that calling functions declared as `inline` from Java is  not (and most likely will never be) supported, since there is no symbol to look up for them. Therefore, some libraries exposing essential functionality through `inline` functions simply won't work.
 
> 5. if a library header isn't there, suggest the user which packages he should install (I have ubuntu/debian in mind, but this applies to MacOSX as well)

In my opinion this is impossible to manage (regarding non-deterministic package names on different distributions), else many compilers would have implemented it already. Of course, it is possible for a small subset of libraries **and** distributions using some kind of lookup table, but this is not something I would like to maintain personally.

> 
> Ps: I also haven't still figured out why:
> 
> * this:
> 
> ```
>                 target.tasks.withType<JavaCompile> {
>                     options.apply {
>                         isFork = true
>                         forkOptions.javaHome = target.file(jex.javaHome.get())
>                     }
>                 }
> ```
> 
> fires
> 
> > Must not use `javaHome` property on `ForkOptions` together with `javaCompiler` property
> 
> * the [kotlin counterpart](https://github.com/elect86/test/blob/master/src/main/kotlin/main.kt) of the OpenGL Teapot example is causing me problems and I have no idea why: tons of unresolved, such as `import jdk.incubator.foreign.CLinker`. The [java one](https://github.com/elect86/test/blob/master/src/main/java/Teapot.java) runs flawless though

I haven't worked with Kotlin for quite some now but this error might be caused because of missing `--add-modules` parameters during compiler invocation. This plugin does [add these options to the Java compiler invocation](https://github.com/krakowski/gradle-jextract/blob/master/src/main/groovy/io/github/krakowski/jextract/JextractPlugin.groovy#L52-L54).

**Comment by elect86** [comment] 2021-06-10 08:32
Is your pipeline building for linux?

**Comment by krakowski** [comment] 2021-06-10 18:28
> Is your pipeline building for linux?

Yes, the pipeline builds for Linux (x86_64).

> Edit: I just saw you are building `master`, I need `foreign-jextract`

In my first reply, I mistakenly mentioned the `master` Branch as the source. In fact, the pipeline uses the `foreign-jextract` branch. Feel free to try one of the hosted archives.

> Ps: I don't see the generated sources.. I set `sourceMode.set(true)`, but I still do get just the `.class`es

Although this should not be the cause, please run the `clean` task before switching between source and class mode. This config does work for me.

```
jextract {

    sourceMode = true

    fromHeader("...") {
     // More options here
    }
}
```

> Pps: let me offer you another way instead of sdkman (I'd prefer to not having to install/configuring additional stuff). What about adding a nested section where users can define which kind of jdk17 downloading? Nightly or latest EA?

Like I mentioned you don't have to rely on SDKMAN! or similar tools. Using Gradle's toolchain mechanism it is possible to place the JDK in a non-standard location an point to it via `org.gradle.java.installations.paths`. I will try to adapt this feature within the plugin once I find the time for it.

**Comment by elect86** [comment] 2021-06-14 10:43
Another thing I'd like is that whenever I set `sourceMode` to true, this would generate classes *and* sources. And I'd like this to be the default value

**Comment by krakowski** [comment] 2021-06-16 11:07
> Another thing I'd like is that whenever I set `sourceMode` to true, this would generate classes _and_ sources. And I'd like this to be the default value

What is the use case for this? From my point of view this would only extend the time it takes to build since `jextract` needs to be invoked twice in a row.

**Comment by elect86** [comment] 2021-06-16 11:08
I honestly don't see much of use cases when one wants to get `.class`es only. Sources are always welcome

**Comment by krakowski** [comment] 2021-06-16 11:42
> I honestly don't see much of use cases when one wants to get `.class`es only. Sources are always welcome, especially when we are talking about something automatically generated to bind natives

From what I remember, class file mode uses features which are not available with source mode like [Dynamic Constants](https://openjdk.java.net/jeps/309).

Setting `sourceMode`'s default to `true` is something I can do. The JDK itself uses this mode for generating `jextract`'s bindings for `libclang`, so this seems to be a good default. This change is introduced with https://github.com/krakowski/gradle-jextract/commit/29037cfc31d9268d9c36cd7409b9a7bc9bf0b4dd.

---

I would like to keep the issues organized, so I'm closing this issue for now as it goes far beyond what it was intended for ("How to use it"). Please feel free to open new issues for additional topics.

**Closed by krakowski** 2021-06-16 11:42 UTC
Labels: question
